#banner配置
banner:
  location: banner-boot.txt

#服务配置
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8



#MySQL
#spring:
#  datasource:
#   driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
#   username: root
#   password: 1234

#druid数据源配置
#多数据源 1主1从
  # 使用druid数据源
dataSource:
  main:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: maidao123
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#配置logback日志
logging:
  config: classpath:logback-boot.xml

#es
spring:
  data:
    elasticsearch:
      cluster-name: my-es # 集群名
      #连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: 0.0.0.0:9300
      local: true #是否本地连接
      repositories:
        enabled: true #仓库中数据存储


#rocket mq
rocketmq:
  consumer:
    groupName: ConsumerGroupOne # 消费者的组名
    consumeThreadMin: 2
    consumeThreadMax: 5
    consumeMessageBatchMaxSize: 10
    topics: TopicOne
  producer:
    groupName: ProducerGroupOne # 生产者的组名
    maxMessageSize: 100
    sendMsgTimeout: 1000
    retryTimesWhenSendFailed: 3
  namesrvAddr: 127.0.0.1:9876 # NameServer地址


#binlog配置
binlog:
  serverId: 1
  host: localhost
  port: 3306
  user: root
  password: maidao123
  database:
    table: ygg_sale_platform.product

---
spring:
  profiles: dev

logging:
  level:
    com.project.web: DEBUG


---
spring:
  profiles: test

logging:
  level:
    com.project.web: DEBUG

---
spring:
  profiles: release
