#banner配置
banner:
  location: banner-boot.txt

#服务配置
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8


#配置logback日志
logging:
  config: classpath:logback-boot.xml

#es-jpa方式-引入的jar包版本号要与客户端版本一致
spring:
  data:
    elasticsearch:
      cluster-name: esCluster # 集群名
      #连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: 127.0.0.1:9300
      local: true #是否本地连接
      repositories:
        enabled: true #仓库中数据存储

#es-RestClient方式
es:
  host: 127.0.0.1
  port: 9200
  index:


---
spring:
  profiles: dev

logging:
  level:
    com.project.web: DEBUG

---
spring:
  profiles: test

logging:
  level:
    com.project.web: DEBUG

---
spring:
  profiles: release
