server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com:project:entity

#MySQL
spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
   username: root
   password: 1234

#druid数据源配置
#多数据源 1主1从
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  username: root
  password: 1234
  driver-class-name: com.mysql.jdbc.Driver
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQueryTimeout: 900000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
#==========end==========
