#banner配置
banner:
  location: banner-boot.txt

#服务配置
server:
  port: 8084
  tomcat:
    uri-encoding: utf-8


#配置logback日志
logging:
  config: classpath:logback-boot.xml


# canal配置
canal:
  ip: 192.168.154.231
  port: 11111
  userName: admin
  password: 4ACFE3202A5FF5CF467898FC58AAB1D615029441
  sap_system:
    schema: sap_system
    destination: example
  canal_manage:
    schema: canal_manage
    destination: example2

---
spring:
  profiles: dev

logging:
  level:
    com.project.web: DEBUG

---
spring:
  profiles: test

logging:
  level:
    com.project.web: DEBUG

---
spring:
  profiles: release
